### ISSUE TITLE
Unable to login due to invalid credentials - fix detailed inside

### ISSUE THREAD

**Issue by robintoy** [mattrayner/pod-point-home-assistant-component#40]
## Configuration

```yaml

Status: 401
Code: Unauthorised
Title: Authentication is required 
Detail: the user credentials were incorrect

```

## Describe the bug
Tried to turn off charging to be displayed with an error saying it could not perform the action and needed to be Authenticated. 

Reloaded the extension via hacs which then required a reboot of Home Assistant. After this was successful Home Assistant said we needed to re-configure it to which I tried to find it would not longer accept my correct user name and password leaving me to revert to the Podpoint app. 

## Debug log

```text

Add your logs here.

```
