### ISSUE TITLE
Smart Charging/Charging Allowed Error

### ISSUE THREAD

**Issue by townsmcp** [mattrayner/pod-point-home-assistant-component#75]
## Version of the custom_component
Version 2.0.5 of custom component.
Core = 2025.2.4
Supervisor = 2025.02.1

## Describe the bug
For the last few days, I have been observing a bit of an odd one. I have checked the logs and can see the below issue being reported. I am not sure if this error is what is causing my issue.
I use the Charging Allowed switch as part of automations - when the car is allowed to charge, or after the car has left home after a charge, my automations turn the switch back on. At the end of charging (car battery at 100%) I have an automation that turns the switch off.
These automations have been working flawlessly up to the last few days (I guess since updating to core 2025.2.4).

What I am observing now is when the car leaves home and the automation turns the Charging Allowed switch back on, when the car then comes home and I plug the car in, even though the switch is set to on in HA I do not get a charge. If I go into the Pod Point app it now shows 'Paused' and no matter how much tinkering I do in HA I cannot get the Pod to start the charge session (to be clear, I do not have any schedules set in the PP app and HA Smart Charge Mode is set to ON)

## Debug log

```text

Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 12:50:23 pm (1 occurrences)
Last logged: 12:50:23 pm

Detected blocking call to import_module with args ('custom_components.pod_point',) in /usr/src/homeassistant/homeassistant/loader.py, line 1075: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 340, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)

```
I also do have a few other references to Pod Point integration if I do debug logging:

[home-assistant_pod_point_2025-02-17T16-45-12.625Z.log](https://github.com/user-attachments/files/18828415/home-assistant_pod_point_2025-02-17T16-45-12.625Z.log)

**Comment by br3mer** [comment]
I'm seeing similar behaviour, with Charging Allowed seemingly having no affect anymore. I'm suspecting it might be something on PodPoint's end as I'm still on 2025.2.1. I had no schedules set but now it seems to add 0hr schedules and activate them by itself, resulting in it either being at Charging Paused or Waiting For Schedule 

Interestingly I can't get it to stop charging now

My last successful charge using Charging Allowed was 14/02/25

```
2025-02-17 18:05:53.830 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.pod_point',) in /usr/src/homeassistant/homeassistant/loader.py, line 1075: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 340, in _async_setup_component
    component = await integration.async_get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
```

**Comment by townsmcp** [comment]
@br3mer thanks for confirming you are still on 2025.2.1 and getting the issue.
I did observe the problem for the first time on Saturday (15th) evening (around 10:30pm). Friday worked fine but the car was plugged in around 3:30pm - just a guess but sounds like the update by PP (assuming that is the issue) would have been done end of day Friday? lol not a good time to deploy code updates really!

Where are you observing the 0 hour schedule? In the app, I am seeing this (but I have had to set a 12 hour override charge just to get it working):

![Image](https://github.com/user-attachments/assets/ba82675d-955b-44c3-bf6b-224292d9ab6f)

**Comment by townsmcp** [comment]
@br3mer has everything started working for you again? It has for me so I’m happy to close this issue if you are good as well

**Comment by nickpearce95** [comment]
Hi @townsmcp  @br3mer - I seem to be having a similar issue here. I use a sensor from Octopus Energy to turn the 'Charging Allowed' toggle on and off overnight to charge my car in the cheapest slots. For the last few days, despite the charging allowed toggle being on, it flips to pending for 5 mins and then seems to get stuck in 'Charging Paused' status (suspended-evse). Seems like pod point are expecting there to be a schedule maintained in this status now?

**Comment by townsmcp** [comment]
@nickpearce95 Sounds like your setup is similar to my one (I am on IOG and have the untethered PodPoint - I have a OHME Go plugged in to the PP front panel which only comes alive when the car is plugged in).
When did you last try to charge the car? Last night was the first time since last Friday that everything just worked as normal - I went out in the car yesterday (noticed the smart charge went to on while out by the HA automations and the PP app wasnt showing 'Charging paused'), and when I got home and plugged in my automations all kicked in and the OHME came on, got its charging slots and car started to charge - for my unit, its like PP fixed the problem for schedule.

**Comment by nickpearce95** [comment]
@townsmcp last night was my most recent attempt - I have a tethered charger and my car isn’t compatible with the intelligent octopus tariff so was using octopus agile with a target rate sensor via the bottle cap Dave integration. Need a fully charged car for a long journey tomorrow so I’ve disabled this for now and will do some more testing over the weekend to try and figure it out!

**Comment by townsmcp** [comment]
@nickpearce95 damn. Maybe PP have found the issue with the code update form last Friday (assuming there was a code update) and are in the process of rolling it all out?

My car isnt IOG compatible either. Before getting the car I had a tethered PP3 installed. I started out on Octopus Go. I then managed to get hold of a 3 pin OHME Go so was charging off a normal UK socket and moved over to IOG. This worked well. But I wasnt happy with where the 3 pin circuit also had an inflatable hot tub on it and I was overloading that circuit when the hot tub heater was on. I setup automations in HA to ensure the hot tub heater was not allowed to come on when the car was charging but in the end this meant the tub wasnt getting up to temperature. So I managed to find an OHME Go type 2/type 2 cable and then managed to find a faulty PP3 untethered unit - I only needed the face plate with the type 2 connection. I swapped over the PP faceplate to untethered and now am very happy with the setup and am still on IOG

**Comment by br3mer** [comment]
@townsmcp  I've just done a quick test and it's going back to suspended-evse when charging allowed is on.

Turning charging allowed on seems to wipe the schedule set in the app, then turning it off again shows a zero hour schedule

![Image](https://github.com/user-attachments/assets/f6eb1b06-5536-401a-b6df-c5893f299079)

**Comment by townsmcp** [comment]
@br3mer I'm seeing slightly different in the app. I see the following (I have no schedule set in the app):

![Image](https://github.com/user-attachments/assets/af69d946-4239-4c8d-8b55-8a5ee6d15be7)
![Image](https://github.com/user-attachments/assets/53eccbf4-b5eb-49ac-af5e-c38858b57f68)
However, I now have the problem back (maybe it was just a fluke for me the other day?)
And I am also seeing a state/charging state of `suspended-evse`.

@mattrayner any ideas what is happening? Are you seeing similar issue?
My attributes are:
```
options:
  - available
  - unavailable
  - charging
  - out-of-service
  - waiting-for-schedule
  - connected-waiting-for-schedule
  - suspended-ev
  - suspended-evse
  - idle
  - pending
attribution: Data provided by https://pod-point.com/
id: XXXXX
integration: pod_point
suggested_area: Outside
total_kwh: 5276.999999999997
total_charge_seconds: 321840
current_kwh: 0
charge_mode: Smart
name: null
ppid: PSL-XXXXXX
payg: false
home: true
public: false
evZone: false
location:
  lat: 51.XXXXXX
  lng: 0.XXXXXXX
address_id: XXXXX0
description: ""
commissioned_at: "2022-02-12T09:00:00+00:00"
created_at: "2022-07-01T15:23:59+00:00"
last_contact_at: "2025-02-20T16:20:51+00:00"
contactless_enabled: false
unit_id: XXXXX3
timezone: UTC
model:
  id: 231
  name: XXXXXXX-ACA
  vendor: Pod Point
  supports_payg: false
  supports_ocpp: false
  supports_contactless: false
  image_url: >-
    https://d34odvqm45w0od.cloudfront.net/pod_model_svgs/home-charge-tethered-v3.svg
price: null
statuses:
  - id: 2
    name: Charging
    key_name: charging
    label: Charging
    door: A
    door_id: 1
unit_connectors:
  - connector:
      id: 248
      door: A
      door_id: 1
      power: 7
      current: 32
      voltage: 230
      charge_method: Single Phase AC
      has_cable: true
      socket:
        type: IEC 62196-2 Type 2
        description: Type 2 socket
        ocpp_name: sType2
        ocpp_code: 3
charge_schedules:
  - uid: XXXXXX
    start_day: 1
    start_time: "00:00:00"
    end_day: 1
    end_time: "00:00:01"
    status:
      is_active: false
  - uid: XXXXXXX
    start_day: 2
    start_time: "00:00:00"
    end_day: 2
    end_time: "00:00:01"
    status:
      is_active: false
  - uid: XXXXXXXX
    start_day: 3
    start_time: "00:00:00"
    end_day: 3
    end_time: "00:00:01"
    status:
      is_active: false
  - uid: fXXXXXXX
    start_day: 4
    start_time: "00:00:00"
    end_day: 4
    end_time: "00:00:01"
    status:
      is_active: false
  - uid: XXXXX
    start_day: 5
    start_time: "00:00:00"
    end_day: 5
    end_time: "00:00:01"
    status:
      is_active: false
  - uid: XXXXXX
    start_day: 6
    start_time: "00:00:00"
    end_day: 6
    end_time: "00:00:01"
    status:
      is_active: false
  - uid: XXXXXXX
    start_day: 7
    start_time: "00:00:00"
    end_day: 7
    end_time: "00:00:01"
    status:
      is_active: false
total_cost: 63765
firmware:
  serial_number: null
  version_info: null
  update_status: null
charge_override: null
offering_energy: false
last_message_at: "2025-02-20T16:59:57+00:00"
charging_state: suspended-evse
connectivity_status:
  ppid: PSL-XXXXX
  connected_components:
    - evses
  evses:
    - id: 1
      architecture: arch3
      connectivityState:
        protocol: POW
        connectivityStatus: ONLINE
        signalStrength: -73
        lastMessageAt: "2025-02-20T16:59:57+00:00"
        connectionStartedAt: "2025-02-20T16:45:58.330000+00:00"
        connectionQuality: 3
      connectors:
        - id: 1
          door: A
          chargingState: SUSPENDED_EVSE
      energyOfferStatus:
        isOfferingEnergy: false
        reason: CHARGE_SCHEDULE
        until: "2025-02-21T00:00:00+00:00"
        randomDelay: null
        doNotCache: false
state: suspended-evse
device_class: enum
entity_picture: /api/pod_point/static/2c-03.png
icon: mdi:ev-plug-type2
friendly_name: PSL-XXXXX Status
```
